name: grasp
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - icc_rt=2019.0.0=h0cc432a_1
  - intel-openmp=2019.3=203
  - mkl=2019.3=203
  - mkl_fft=1.0.10=py37h14836fe_0
  - mkl_random=1.0.2=py37h343c172_0
  - numpy=1.16.2=py37h19fb1c0_0
  - numpy-base=1.16.2=py37hc3f5095_0
  - openssl=1.1.1b=he774522_1
  - pip=19.0.3=py37_0
  - python=3.7.3=h8c8aaf0_0
  - setuptools=41.0.0=py37_0
  - sqlite=3.27.2=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_0
  - wheel=0.33.1=py37_0
  - wincertstore=0.2=py37_0
  - xlsxwriter=1.1.6=py_0
prefix: D:\Miniconda3\envs\grasp

